### ISSUE TITLE
Do you will updating configuration vagrant?

### ISSUE THREAD

**Issue by ghost** [WebDevArchive/webdev-env#1]
Vagrant scotch-box updating to 2.5. I should to change the configuration?

Vagrant  scotch-box обновили до 2.5. Я должен менять конфигурации?

**Comment by Stas404** [comment]
1) Если уже используется эта конфигурация, то менять не обязательно. Достаточно только обновить сам бокс: `vagrant box update`.

2) Если ставится по новой, то в последней версии "scotch-box" они встроили механизм добавления виртуальных хостов, подобный тому, который используется здесь. Видимо, как раз, после описания и статьи на Хабре :)
Таким образом, можно склонироваться от них напрямую (https://github.com/scotch-io/scotch-box) и использовать их механизм:
https://scotch.io/bar-talk/announcing-scotch-box-2-0-our-dead-simple-vagrant-lamp-stack-improved#multiple-domains-(virtual-hosts)

3) Возможно, обновлю конфигурацию и добавлю несколько полезных для webdev скриптов с учетом того, что часть из них уже добавили в сам "scotch-box".
